env: panda-pick-and-place-sparse
wrappers:
  - step-api-compatibility
  - time-feature
dataset: datasets/panda_pick_and_place_sparse_1m_expert.pkl
save_path: trained/bc_panda_pick_and_place_sparse
seed: 1234
render: False
extractor_type: dict

actor_type: bc
model_kwargs:
  hidden_sizes: [512, 512]
  # activation_function: relu
  # dropout: 0.1

training_kwargs:
  num_epochs: 120
  batch_size: 64
  learning_rate: 0.0001
  # weight_decay: 0.0001
  # warmup_ratio: 0.1
  # optimizer: adamw_torch
  # max_grad_norm: 0.25

eval_kwargs:
  num_timesteps: 10000
