env: halfcheetah
wrappers:
  - step-api-compatibility
dataset: cache/halfcheetah-medium-v2.pkl
policy_type: dt
save_path: results/halfcheetah-dt
seed: 1234
render: False

policy_kwargs:
  return_scale: 1000.0
  K: 20
  max_ep_len: 1000
  scale: 1000
  hidden_size: 128
  n_layer: 3
  n_head: 1
  activation_function: relu
  dropout: 0.1

training_kwargs:
  num_epochs: 120
  batch_size: 64
  learning_rate: 0.0001
  weight_decay: 0.0001
  warmup_ratio: 0.1
  optimizer: adamw_torch
  max_grad_norm: 0.25

eval_kwargs:
  goal_return: 6000
  num_episodes: 10
