env: halfcheetah
wrappers:
  - step-api-compatibility
dataset: cache/halfcheetah-medium-v2.pkl
agent_type: nanodt
save_path: trained/nanodt_halfcheetah
seed: 1234
render: False

model_kwargs:
  n_layer: 3
  n_head: 1
  n_embd: 128
  dropout: 0.1
  K: 20
  state_dim: 17
  act_dim: 6
  act_discrete: False
  max_ep_len: 1000

training_kwargs:
  batch_size: 64
  learning_rate: 0.0001
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.999
  max_iters: 100_000
  warmup_iters: 10_000
  lr_decay_iters: 100_000
  min_lr: 0.000001
  device: mps
  pct_traj: 1.0
  reward_scale: 1000.0
  grad_clip: 0.25
  always_save_checkpoint: True
  out_dir: trained/nanodt_halfcheetah

eval_kwargs:
  goal_return: 6000
  num_timesteps: 10000
