PandaPushDense-v3:
  n_timesteps: 1_000_000
  policy: 'MultiInputPolicy'
  buffer_size: 1_000_000
  batch_size: 2048
  gamma: 0.95
  learning_rate: 0.001
  tau: 0.05
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs:
    goal_selection_strategy: future
    n_sampled_goal: 4
  policy_kwargs: 
    net_arch: [512, 512, 512]
    n_critics: 2
  # n_envs: 4
  # gradient_steps: -1

PandaPush-v3:
  n_timesteps: 1_000_000
  policy: 'MultiInputPolicy'
  buffer_size: 1_000_000
  batch_size: 2048
  gamma: 0.95
  learning_rate: 0.001
  tau: 0.05
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs:
    goal_selection_strategy: future
    n_sampled_goal: 4
  policy_kwargs: 
    net_arch: [512, 512, 512]
    n_critics: 2

PandaPickAndPlaceDense-v3:
  n_timesteps: 1_000_000
  policy: 'MultiInputPolicy'
  buffer_size: 1_000_000
  batch_size: 2048
  gamma: 0.95
  learning_rate: 0.001
  tau: 0.05
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs:
    goal_selection_strategy: future
    n_sampled_goal: 4
  policy_kwargs: 
    net_arch: [512, 512, 512]
    n_critics: 2

PandaPickAndPlace-v3:
  n_timesteps: 1_000_000
  policy: 'MultiInputPolicy'
  buffer_size: 1_000_000
  batch_size: 2048
  gamma: 0.95
  learning_rate: 0.001
  tau: 0.05
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs:
    goal_selection_strategy: future
    n_sampled_goal: 4
  policy_kwargs: 
    net_arch: [512, 512, 512]
    n_critics: 2

PandaReachDense-v3:
  n_timesteps: 20_000
  policy: 'MultiInputPolicy'
  buffer_size: 1_000_000
  batch_size: 2048
  gamma: 0.95
  learning_rate: 0.001
  tau: 0.05
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs:
    goal_selection_strategy: future
    n_sampled_goal: 4
  policy_kwargs: 
    net_arch: [512, 512, 512]
    n_critics: 2

PandaReach-v3:
  n_timesteps: 20_000
  policy: 'MultiInputPolicy'
  buffer_size: 1_000_000
  batch_size: 2048
  gamma: 0.95
  learning_rate: 0.001
  tau: 0.05
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs:
    goal_selection_strategy: future
    n_sampled_goal: 4
  policy_kwargs: 
    net_arch: [512, 512, 512]
    n_critics: 2